loggin:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s %(levelname)s %(threadName)s %(name)s %(message)s"
            datefmt: "%Y/%m/%d %H:%M:%S"

    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout

        access_file_handler:
            class: logging.handlers.TimedRotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: log/move.log
            backupCount: 30
            encoding: utf8
            when: midnight
            interval: 1
            delay: True

    root:
        level: INFO
        handlers: [console, access_file_handler]
move:
    debug: true
    video_device: 1 #para webcam 0
    #video_device: "video/VID_20171021_144029337.mp4"
    canvas:
        defaults:
            width: 320
            height: 240
            hflip: false
            vflip: false
            rotation: 0
            frame_rate: 25
            windows_on: true

    move_entity:
        bigger: 2
        min_area: 600
        blur_size: 5
        threshold_sensitivity: 25
        movelist_timeout: 0.5
        inout_reverse: false

recorder:
    output_file: 'saida_video/output.avi'
    fps: 20
    width: 320
    height: 240
    codec: DIV3 # MPEG 4.3
    #codec: MP42 # MPEG 4.2
    #codec: PIM1 # MPEG-1
    #codec: DIVX # MPEG-4 = MPEG-1
    #codec: MJPG # Motion Jpeg
    #codec: U263 # H263
    #codec: I263 # H263I
    #codec: FLV1 # FLV
    #codec: XVID # ??
